Repository spheronFdn/docs, pull requests merged in 2023-09, with the labels that each got.

#80 Update steps in marketplace apps
  pages.config.ts
  pages/marketplace-guide/arbitrum-one.mdx
  pages/marketplace-guide/deso.mdx
  pages/marketplace-guide/drupal.mdx
  pages/marketplace-guide/filecoin.mdx
  pages/marketplace-guide/grafana.mdx
  pages/marketplace-guide/hypersign.mdx
  pages/marketplace-guide/ipfs.mdx
  pages/marketplace-guide/jupyter.mdx
  pages/marketplace-guide/kyve.mdx
  pages/marketplace-guide/mantle-dtl.mdx
  pages/marketplace-guide/mantle-verifier.mdx
  pages/marketplace-guide/massbit-gateway.mdx
  pages/marketplace-guide/mongodb.mdx
  pages/marketplace-guide/mysql.mdx
  pages/marketplace-guide/postgresql.mdx
  pages/marketplace-guide/redis.mdx
  pages/marketplace-guide/reef.mdx
  pages/marketplace-guide/stride.mdx
  pages/marketplace-guide/substrate.mdx
  pages/marketplace-guide/sui.mdx
  pages/marketplace-guide/vault.mdx
Labels: documentation

#83 Update steps in server guide
  pages/server-guide/django.mdx
  pages/server-guide/express.mdx
  pages/server-guide/go.mdx
  pages/server-guide/nest.mdx
  pages/server-guide/nextjs.mdx
  pages/server-guide/rails.mdx
  pages/server-guide/rust.mdx
Labels: documentation

#82 Update steps in cluster page
  pages/compute/cluster.mdx
Labels: documentation

#87 Update compute nomenclature
  components/type.tsx
  pages.config.ts
  pages/compute/_meta.json
  pages/compute/cluster.mdx
  pages/compute/scaling/_meta.json
  pages/compute/type.mdx
  pages/compute/type/_meta.json
  pages/compute/type/autoscale.mdx
  pages/compute/type/on-demand.mdx
  pages/compute/type/spot.mdx
  pages/marketplace-guide/arbitrum-one.mdx
  pages/marketplace-guide/deso.mdx
  pages/marketplace-guide/drupal.mdx
  pages/marketplace-guide/filecoin.mdx
  pages/marketplace-guide/grafana.mdx
  pages/marketplace-guide/hypersign.mdx
  pages/marketplace-guide/ipfs.mdx
  pages/marketplace-guide/jupyter.mdx
  pages/marketplace-guide/kyve.mdx
  pages/marketplace-guide/mantle-dtl.mdx
  pages/marketplace-guide/mantle-verifier.mdx
  pages/marketplace-guide/massbit-gateway.mdx
  pages/marketplace-guide/mongodb.mdx
  pages/marketplace-guide/mysql.mdx
  pages/marketplace-guide/postgresql.mdx
  pages/marketplace-guide/redis.mdx
  pages/marketplace-guide/reef.mdx
  pages/marketplace-guide/stride.mdx
  pages/marketplace-guide/substrate.mdx
  pages/marketplace-guide/sui.mdx
  pages/marketplace-guide/vault.mdx
  pages/server-guide/django.mdx
  pages/server-guide/express.mdx
  pages/server-guide/go.mdx
  pages/server-guide/nest.mdx
  pages/server-guide/nextjs.mdx
  pages/server-guide/rails.mdx
  pages/server-guide/rust.mdx
Labels: documentation, update

#70 Add docs for storage version two
  components/sdk.tsx
  pages.config.ts
  pages/sdk/_meta.json
  pages/sdk/browser.mdx
  pages/sdk/storage-v2.mdx
  pages/sdk/storage.mdx
Labels: documentation, feature

#88 Add disclaimer in Spot compute
  pages/compute/type/autoscale.mdx
  pages/compute/type/on-demand.mdx
  pages/compute/type/spot.mdx
Labels: documentation, feature

#89 Replace discord icon with community icon
  assets/community.tsx
  assets/github.tsx
  styles/global.module.css
  theme.config.tsx
Labels: documentation, update

#94 Add inBackground parameter to the pinCid function
  pages/sdk/storage-v2.mdx
Labels: documentation, update

#105 Fix the migrateStaticSiteOrgToStorage parameters
  pages/sdk/storage-v2.mdx
Labels: documentation, update

#91 Add plans section to compute docs
  components/plans-card.tsx
  components/plans.tsx
  pages.config.ts
  pages/compute/_meta.json
  pages/compute/plans.mdx
  styles/plans.module.css
Labels: documentation, feature

#92 Add upload section in storage docs
  pages.config.ts
  pages/_meta.json
  pages/storage/_meta.json
  pages/storage/upload.mdx
Labels: documentation, feature

#93 Add uploads section under buckets
  pages/storage/_meta.json
  pages/storage/billing.mdx
  pages/storage/buckets.mdx
  pages/storage/buckets/_meta.json
  pages/storage/buckets/domain.mdx
  pages/storage/buckets/ipns.mdx
  pages/storage/comparision.mdx
  pages/storage/encryption.mdx
  pages/storage/limitations.mdx
  pages/storage/migration.mdx
Labels: documentation, feature

#95 Add IPNS section under Buckets
  pages/storage/buckets.mdx
  pages/storage/buckets/ipns.mdx
Labels: documentation, feature

#96 Add dedicated gateways link in storage section
  pages/gateways/dedicated.mdx
  pages/storage/_meta.json
  pages/storage/upload.mdx
Labels: documentation, feature

#98 Add domains section under buckets
  pages/storage/buckets/_meta.json
  pages/storage/buckets/domain.mdx
  pages/storage/buckets/ens.mdx
  pages/storage/buckets/handshake.mdx
  pages/storage/buckets/ipns.mdx
Labels: documentation, feature

#99 Add migration docs from <v2 to >=v2
  pages/sdk/storage-v2.mdx
  pages/storage/migration.mdx
Labels: documentation, feature

#100 Add encryption and access control docs
  pages/sdk/browser.mdx
  pages/storage/encryption.mdx
Labels: documentation, feature
