Repository spheronFdn/docs, pull requests merged in 2023-10, with the labels that each got.

#101 Add browser upload sdk vs storage sdk
  pages/storage/comparision.mdx
Labels: documentation, feature

#102 Add Rate Limits section under Storage
  pages/storage/_meta.json
  pages/storage/rate-limits.mdx
Labels: documentation, feature

#103 Add billing section under Storage
  pages.config.ts
  pages/storage/billing.mdx
  pages/storage/migration.mdx
Labels: documentation, feature

#104 Add storage card in quick start and Add navigation in storage docs
  components/quick-start.tsx
  pages.config.ts
  pages/storage/_meta.json
  pages/storage/billing.mdx
  pages/storage/buckets.mdx
  pages/storage/buckets/domain.mdx
  pages/storage/buckets/ens.mdx
  pages/storage/buckets/handshake.mdx
  pages/storage/buckets/ipns.mdx
  pages/storage/comparision.mdx
  pages/storage/encryption.mdx
  pages/storage/limitations.mdx
  pages/storage/migration.mdx
  pages/storage/rate-limits.mdx
Labels: documentation, feature

#109 Add Storage doc
  components/quick-start.tsx
  pages.config.ts
  pages/sdk/browser.mdx
  pages/sdk/storage-v2.mdx
  pages/storage/_meta.json
  pages/storage/billing.mdx
  pages/storage/buckets.mdx
  pages/storage/buckets/domain.mdx
  pages/storage/buckets/ens.mdx
  pages/storage/buckets/handshake.mdx
  pages/storage/buckets/ipns.mdx
  pages/storage/comparision.mdx
  pages/storage/encryption.mdx
  pages/storage/limitations.mdx
  pages/storage/migration.mdx
  pages/storage/rate-limits.mdx
Labels: documentation

#112 Add usage section for each type of service
  pages.config.ts
  pages/compute/usage.mdx
  pages/static/_meta.json
  pages/static/usage.mdx
  pages/storage/_meta.json
  pages/storage/usage.mdx
Labels: documentation, feature

#114 Add docs for coupon credits
  pages.config.ts
  pages/billing/_meta.json
  pages/billing/coupons.mdx
  pages/billing/credits.mdx
Labels: documentation, update

#118 Add copy functionality
  next.config.js
Labels: documentation, feature
